-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ========================================================
-- User Management Table (for Spring Boot Auth)
-- ========================================================
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  roles VARCHAR(255) NOT NULL DEFAULT 'ROLE_USER',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create default admin user (password: 123456)
-- BCrypt hash generated by Java: BCryptPasswordEncoder().encode("123456")
-- This hash is compatible with Spring Security's BCryptPasswordEncoder
INSERT INTO users (username, password, email, roles) 
VALUES ('admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', 'admin@example.com', 'ROLE_ADMIN,ROLE_USER')
ON CONFLICT (username) DO NOTHING;

-- ========================================================
-- Documents metadata
-- ========================================================
CREATE TABLE IF NOT EXISTS kb_document (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id text NOT NULL,
  kb_id text NOT NULL,
  status text NOT NULL CHECK (status IN ('PENDING', 'PROCESSING', 'READY', 'ERROR')),
  chunk_count int NOT NULL DEFAULT 0,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Document chunks
CREATE TABLE IF NOT EXISTS kb_chunk (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  doc_id uuid NOT NULL,
  tenant_id text NOT NULL,
  kb_id text NOT NULL,
  seq_no int NOT NULL,
  content text NOT NULL,
  content_sha256 text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Idempotent uniqueness on chunk order per document
CREATE UNIQUE INDEX IF NOT EXISTS idx_kb_chunk_doc_seq ON kb_chunk (doc_id, seq_no);

-- ========================================================
-- Chat Sessions
-- ========================================================
CREATE TABLE IF NOT EXISTS sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES users(id),
  title VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ========================================================
-- Chat Messages
-- ========================================================
CREATE TABLE IF NOT EXISTS chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  role VARCHAR(50) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
